#task h3.1: Сделать свое решение для этого соревнования https://www.kaggle.com/competitions/digit-recognizer
# Результат: опубликовать решение в разделе. После отправить мне через сайт ку решение и какой у вас получился скор

In [12]:
import pandas as pd

In [13]:
data = pd.read_csv('sample_submission.csv')
data.head()

   ImageId  Label
0        1      0
1        2      0
2        3      0
3        4      0
4        5      0

In [14]:
data = pd.read_csv('test.csv')
data.head()

,pixel0,pixel1,pixel2,pixel3,pixel4,pixel5,pixel6,pixel7,pixel8,pixel9,...,pixel774,pixel775,pixel776,pixel777,pixel778,pixel779,pixel780,pixel781,pixel782,pixel783
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [15]:
data = pd.read_csv('train.csv')
data.head()

,label,pixel0,pixel1,pixel2,pixel3,pixel4,pixel5,pixel6,pixel7,pixel8,...,pixel774,pixel775,pixel776,pixel777,pixel778,pixel779,pixel780,pixel781,pixel782,pixel783
0,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,4,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [16]:
import pandas as pd
import numpy as np
from keras.models import Sequential
from keras.layers import Dense, Flatten, Input

# Загрузка данных
train_data = pd.read_csv('C:/Users/285/Desktop/data_science/HomeWork12 DL 3 lesson/train.csv')
test_data = pd.read_csv('C:/Users/285/Desktop/data_science/HomeWork12 DL 3 lesson/test.csv')

# Предобработка данных
X_train = train_data.drop('label', axis=1).values
y_train = train_data['label'].values

# Измените форму X_train на (количество образцов, 28, 28)
X_train = X_train.reshape(-1, 28, 28)

# Создание модели
model = Sequential()
model.add(Input(shape=(28, 28)))  # Используйте Input для указания формы
model.add(Flatten())
model.add(Dense(128, activation='relu'))
model.add(Dense(10, activation='softmax'))

# Компиляция модели
model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])

# Обучение модели
model.fit(X_train, y_train, epochs=10, batch_size=32)

# Предсказание на тестовых данных
X_test = test_data.values.reshape(-1, 28, 28)  # Измените форму тестовых данных
predictions = model.predict(X_test)
predicted_labels = predictions.argmax(axis=1)

# Создание файла для отправки
submission = pd.DataFrame({'ImageId': range(1, len(predicted_labels) + 1), 'Label': predicted_labels})
submission.to_csv('submission.csv', index=False)

print("Файл 'submission.csv' создан успешно!")

Epoch 1/10
1313/1313 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.7972 - loss: 9.0871
Epoch 2/10
1313/1313 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.8946 - loss: 0.4687
Epoch 3/10
1313/1313 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.9179 - loss: 0.3247
Epoch 4/10
1313/1313 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.9291 - loss: 0.2849
Epoch 5/10
1313/1313 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.9333 - loss: 0.2522
Epoch 6/10
1313/1313 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.9410 - loss: 0.2254
Epoch 7/10
1313/1313 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.9449 - loss: 0.2219
Epoch 8/10
1313/1313 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.9506 - loss: 0.1942
Epoch 9/10
1313/1313 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.9550 - loss: 0.1762
Epoch 10/10
1313/1313 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.9588 - loss: 0.1625
875/875 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step
Файл 'submission.csv' создан успешно!

In [17]:
data = pd.read_csv('submission.csv')
data.head()

   ImageId  Label
0        1      2
1        2      0
2        3      9
3        4      3
4        5      5